### ISSUE TITLE
Error when importing qp version 0.7.1 with scipy 1.7.3

### ISSUE THREAD

**Issue by DManowitz** [LSSTDESC/qp#131]
When I try to import qp, I get the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\...\lib\site-packages\qp\__init__.py", line 6, in <module>
    from .spline_pdf import *
  File "C:\...\lib\site-packages\qp\spline_pdf.py", line 11, in <module>
    from qp.pdf_gen import Pdf_rows_gen
  File "C:\...\lib\site-packages\qp\pdf_gen.py", line 24, in <module>
    from scipy.stats._distn_infrastructure import rv_continuous_frozen
ImportError: cannot import name 'rv_continuous_frozen' from 'scipy.stats._distn_infrastructure' (C:\...\lib\site-packages\scipy\stats\_distn_infrastructure.py)
```

I have qp 0.7.1 and scipy 1.7.3 installed.  I have verified this error in both Python 3.7 and Python 3.8.

**Comment by sschmidt23** [comment]
I think the requirements.txt for qp is just out of date, and we should really have scipy>=1.9, same as what we have in RAIL (which effectively means python>=3.8 since scipy stopped supporting python 3.7 for recent releases).  It looks like our Github action is grabbing scipy 1.9.3 by default so we did not catch the outdated req. Can someone who has been working on qp more recently confirm this?

**Comment by BStoelzner** [comment]
Possibly related to this error, the code in mixmod_examples.ipynb throws an error when calling the qp.convert function. This seems to be related to the scipy rv_frozen.rvs method. I'm running python 3.11 and scipy 1.11.1.
See here: https://gist.github.com/BStoelzner/a87e6cd6b75171c852361b0f44ee0849
